# -*- coding: utf-8 -*-
"""Assignment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XzV1y-vX4JHFKKrvC6AgfnpxLp8E7RCL
"""

!pip install gdown

# Fear & Greed dataset
!gdown --id 1PgQC0tO8XN-wqkNyghWc_-mnrYv_nhSf -O fear_greed_index.csv

# Hyperliquid historical trader data
!gdown --id 1IAfLZwu6rJzyWKgBToqwSmmVYU6VbjVs -O historical_data.csv

import pandas as pd

trades = pd.read_csv("historical_data.csv")
sentiment = pd.read_csv("fear_greed_index.csv")

trades.head(), sentiment.head()

trades.head()
trades.info()

sentiment.head()
sentiment.info()

import pandas as pd

# Convert time/dates
trades['time_parsed'] = pd.to_datetime(trades['Timestamp IST'], errors='coerce', dayfirst=True)
trades['date'] = trades['time_parsed'].dt.date

sentiment['Date'] = pd.to_datetime(sentiment['date'], errors='coerce')
sentiment['Date'] = sentiment['Date'].dt.date
sentiment.rename(columns={'classification':'sentiment'}, inplace=True)

trades.head(), sentiment.head()

merged = trades.merge(sentiment, left_on='date', right_on='Date', how='left')
merged.drop(columns=['Date'], inplace=True)

merged.head()

merged['sentiment'].isna().sum()

merged = merged.dropna(subset=['sentiment'])

merged['is_win'] = (merged['Closed PnL'] > 0).astype(int)

performance = merged.groupby('sentiment').agg(
    total_trades=('Closed PnL', 'count'),
    win_rate=('is_win', 'mean'),
    avg_pnl=('Closed PnL', 'mean'),
    total_pnl=('Closed PnL', 'sum'),
    avg_size=('Size USD', 'mean')
).reset_index()

performance

import seaborn as sns
import matplotlib.pyplot as plt

sns.barplot(data=performance, x='sentiment', y='avg_pnl')
plt.title("Average PnL per Trade by Market Sentiment")
plt.show()

sns.barplot(data=performance, x='sentiment', y='win_rate')
plt.title("Win Rate by Market Sentiment")
plt.show()

sns.boxplot(data=merged, x='sentiment', y='Closed PnL')
plt.yscale('symlog')
plt.title("PnL Distribution by Sentiment")
plt.show()